# Generated by Django 5.1.5 on 2026-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_siteconfig_newsarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutblock',
            options={'ordering': ('order',), 'verbose_name': '② About Block', 'verbose_name_plural': '② About Blocks (3 cards giới thiệu)'},
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': '② About Section', 'verbose_name_plural': '② About Section (Nội dung giới thiệu)'},
        ),
        migrations.AlterModelOptions(
            name='bannerslide',
            options={'ordering': ('order',), 'verbose_name': '① Banner Slide', 'verbose_name_plural': '① Banner Slides (Ảnh slider)'},
        ),
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'ordering': ('order',), 'verbose_name': '⑤ Business Category', 'verbose_name_plural': '⑤ Business Categories (Lĩnh vực hoạt động)'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': '⑥ News Article', 'verbose_name_plural': '⑥ News Articles (Tin tức)'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order',), 'verbose_name': '⑦ Partner', 'verbose_name_plural': '⑦ Partners (Đối tác)'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': '⚙ Cấu hình chung (Logo, Liên hệ, Ảnh nền)', 'verbose_name_plural': '⚙ Cấu hình chung (Logo, Liên hệ, Ảnh nền)'},
        ),
        migrations.AlterModelOptions(
            name='statitem',
            options={'ordering': ('order',), 'verbose_name': '④ Stat Item', 'verbose_name_plural': '④ Stat Items (Số liệu ấn tượng)'},
        ),
        migrations.AlterModelOptions(
            name='videosection',
            options={'verbose_name': '③ Video Section', 'verbose_name_plural': '③ Video Section (Video nổi bật)'},
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/'),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='image_ko',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/'),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='image_vi',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/'),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='image_zh',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/'),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='subtitle_ko',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='subtitle_vi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='subtitle_zh',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='title_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_text_en',
            field=models.CharField(default='Tìm hiểu thêm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_text_ko',
            field=models.CharField(default='Tìm hiểu thêm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_text_vi',
            field=models.CharField(default='Tìm hiểu thêm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_text_zh',
            field=models.CharField(default='Tìm hiểu thêm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_vi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_zh',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='label_en',
            field=models.CharField(default='Giới thiệu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='label_ko',
            field=models.CharField(default='Giới thiệu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='label_vi',
            field=models.CharField(default='Giới thiệu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='label_zh',
            field=models.CharField(default='Giới thiệu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(default='Hợp lực', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ko',
            field=models.CharField(default='Hợp lực', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_vi',
            field=models.CharField(default='Hợp lực', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_zh',
            field=models.CharField(default='Hợp lực', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='alt_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='alt_ko',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='alt_vi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='alt_zh',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banners/'),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='image_ko',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banners/'),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='image_vi',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banners/'),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='image_zh',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banners/'),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='title_ko',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='title_vi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='title_zh',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='pages/categories/'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='image_ko',
            field=models.ImageField(blank=True, null=True, upload_to='pages/categories/'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='image_vi',
            field=models.ImageField(blank=True, null=True, upload_to='pages/categories/'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='image_zh',
            field=models.ImageField(blank=True, null=True, upload_to='pages/categories/'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='subtitle_ko',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='subtitle_vi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='subtitle_zh',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='title_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_vi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_zh',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_en',
            field=models.TextField(blank=True, default='', help_text='Mô tả ngắn', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_ko',
            field=models.TextField(blank=True, default='', help_text='Mô tả ngắn', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_vi',
            field=models.TextField(blank=True, default='', help_text='Mô tả ngắn', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_zh',
            field=models.TextField(blank=True, default='', help_text='Mô tả ngắn', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_ko',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_vi',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_zh',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug_ko',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug_vi',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug_zh',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_ko',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_vi',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_zh',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hcm_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hcm_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hcm_vi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hcm_zh',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hn_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hn_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hn_vi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_hn_zh',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_zh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='subtitle_ko',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='subtitle_vi',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='subtitle_zh',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='thumbnail_en',
            field=models.ImageField(blank=True, null=True, upload_to='pages/video/'),
        ),
        migrations.AddField(
            model_name='videosection',
            name='thumbnail_ko',
            field=models.ImageField(blank=True, null=True, upload_to='pages/video/'),
        ),
        migrations.AddField(
            model_name='videosection',
            name='thumbnail_vi',
            field=models.ImageField(blank=True, null=True, upload_to='pages/video/'),
        ),
        migrations.AddField(
            model_name='videosection',
            name='thumbnail_zh',
            field=models.ImageField(blank=True, null=True, upload_to='pages/video/'),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_en',
            field=models.CharField(default='VIDEO NỔI BẬT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_ko',
            field=models.CharField(default='VIDEO NỔI BẬT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_vi',
            field=models.CharField(default='VIDEO NỔI BẬT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_zh',
            field=models.CharField(default='VIDEO NỔI BẬT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='youtube_id_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='youtube_id_ko',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='youtube_id_vi',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='youtube_id_zh',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
