from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_organization_page"),
    ]

    operations = [
        # ==================== RESOURCES PAGE ====================
        migrations.CreateModel(
            name="ResourcesBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, upload_to="resources/banner/")),
                ("image_vi", models.ImageField(blank=True, null=True, upload_to="resources/banner/")),
                ("image_en", models.ImageField(blank=True, null=True, upload_to="resources/banner/")),
                ("image_zh_hans", models.ImageField(blank=True, null=True, upload_to="resources/banner/")),
                ("image_ko", models.ImageField(blank=True, null=True, upload_to="resources/banner/")),
                ("alt", models.CharField(blank=True, default="", max_length=255)),
                ("alt_vi", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("alt_en", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("alt_zh_hans", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("alt_ko", models.CharField(blank=True, default="", max_length=255, null=True)),
            ],
            options={
                "verbose_name": "⑯ Banner (Nguồn lực)",
                "verbose_name_plural": "⑯ Banner (Nguồn lực)",
                "db_table": "pages_resources_banner",
            },
        ),
        migrations.CreateModel(
            name="HumanResources",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="NGUỒN NHÂN LỰC", max_length=255)),
                ("title_vi", models.CharField(default="NGUỒN NHÂN LỰC", max_length=255, null=True)),
                ("title_en", models.CharField(default="NGUỒN NHÂN LỰC", max_length=255, null=True)),
                ("title_zh_hans", models.CharField(default="NGUỒN NHÂN LỰC", max_length=255, null=True)),
                ("title_ko", models.CharField(default="NGUỒN NHÂN LỰC", max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_vi", models.TextField(blank=True, default="", null=True)),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_zh_hans", models.TextField(blank=True, default="", null=True)),
                ("description_ko", models.TextField(blank=True, default="", null=True)),
                ("image", models.ImageField(blank=True, upload_to="resources/human/")),
                ("total_staff", models.CharField(default=">1500", max_length=50)),
                ("total_staff_vi", models.CharField(default=">1500", max_length=50, null=True)),
                ("total_staff_en", models.CharField(default=">1500", max_length=50, null=True)),
                ("total_staff_zh_hans", models.CharField(default=">1500", max_length=50, null=True)),
                ("total_staff_ko", models.CharField(default=">1500", max_length=50, null=True)),
            ],
            options={
                "verbose_name": "⑰ Nguồn nhân lực",
                "verbose_name_plural": "⑰ Nguồn nhân lực",
                "db_table": "pages_human_resources",
            },
        ),
        migrations.CreateModel(
            name="StaffBreakdown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("role", models.CharField(max_length=255)),
                ("role_vi", models.CharField(max_length=255, null=True)),
                ("role_en", models.CharField(max_length=255, null=True)),
                ("role_zh_hans", models.CharField(max_length=255, null=True)),
                ("role_ko", models.CharField(max_length=255, null=True)),
                ("count", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "⑰ Nhân sự chi tiết",
                "verbose_name_plural": "⑰ Nhân sự chi tiết",
                "db_table": "pages_staff_breakdown",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagementSystem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="HỆ THỐNG QUẢN LÝ", max_length=255)),
                ("title_vi", models.CharField(default="HỆ THỐNG QUẢN LÝ", max_length=255, null=True)),
                ("title_en", models.CharField(default="HỆ THỐNG QUẢN LÝ", max_length=255, null=True)),
                ("title_zh_hans", models.CharField(default="HỆ THỐNG QUẢN LÝ", max_length=255, null=True)),
                ("title_ko", models.CharField(default="HỆ THỐNG QUẢN LÝ", max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_vi", models.TextField(blank=True, default="", null=True)),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_zh_hans", models.TextField(blank=True, default="", null=True)),
                ("description_ko", models.TextField(blank=True, default="", null=True)),
                ("slogan", models.TextField(blank=True, default="")),
                ("slogan_vi", models.TextField(blank=True, default="", null=True)),
                ("slogan_en", models.TextField(blank=True, default="", null=True)),
                ("slogan_zh_hans", models.TextField(blank=True, default="", null=True)),
                ("slogan_ko", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name": "⑱ Hệ thống quản lý",
                "verbose_name_plural": "⑱ Hệ thống quản lý",
                "db_table": "pages_management_system",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("name", models.CharField(help_text="VD: ISO 9001:2015", max_length=255)),
                ("name_vi", models.CharField(help_text="VD: ISO 9001:2015", max_length=255, null=True)),
                ("name_en", models.CharField(help_text="VD: ISO 9001:2015", max_length=255, null=True)),
                ("name_zh_hans", models.CharField(help_text="VD: ISO 9001:2015", max_length=255, null=True)),
                ("name_ko", models.CharField(help_text="VD: ISO 9001:2015", max_length=255, null=True)),
                ("title", models.CharField(help_text="VD: Quản lý chất lượng", max_length=255)),
                ("title_vi", models.CharField(help_text="VD: Quản lý chất lượng", max_length=255, null=True)),
                ("title_en", models.CharField(help_text="VD: Quản lý chất lượng", max_length=255, null=True)),
                ("title_zh_hans", models.CharField(help_text="VD: Quản lý chất lượng", max_length=255, null=True)),
                ("title_ko", models.CharField(help_text="VD: Quản lý chất lượng", max_length=255, null=True)),
                ("image", models.ImageField(blank=True, upload_to="resources/certificates/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "⑱ Chứng chỉ ISO",
                "verbose_name_plural": "⑱ Chứng chỉ ISO",
                "db_table": "pages_certificates",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceProjectSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Dự án", max_length=255)),
                ("title_vi", models.CharField(default="Dự án", max_length=255, null=True)),
                ("title_en", models.CharField(default="Dự án", max_length=255, null=True)),
                ("title_zh_hans", models.CharField(default="Dự án", max_length=255, null=True)),
                ("title_ko", models.CharField(default="Dự án", max_length=255, null=True)),
                ("total_projects", models.CharField(default="500 dự án", max_length=100)),
                ("total_projects_vi", models.CharField(default="500 dự án", max_length=100, null=True)),
                ("total_projects_en", models.CharField(default="500 dự án", max_length=100, null=True)),
                ("total_projects_zh_hans", models.CharField(default="500 dự án", max_length=100, null=True)),
                ("total_projects_ko", models.CharField(default="500 dự án", max_length=100, null=True)),
                ("background_image", models.ImageField(blank=True, upload_to="resources/projects/")),
            ],
            options={
                "verbose_name": "⑲ Dự án - Cấu hình",
                "verbose_name_plural": "⑲ Dự án - Cấu hình",
                "db_table": "pages_resource_project_section",
            },
        ),
        migrations.CreateModel(
            name="ResourceProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("name", models.CharField(max_length=500)),
                ("name_vi", models.CharField(max_length=500, null=True)),
                ("name_en", models.CharField(max_length=500, null=True)),
                ("name_zh_hans", models.CharField(max_length=500, null=True)),
                ("name_ko", models.CharField(max_length=500, null=True)),
                ("location", models.CharField(help_text="VD: KCN Đại An mở rộng", max_length=255)),
                ("location_vi", models.CharField(help_text="VD: KCN Đại An mở rộng", max_length=255, null=True)),
                ("location_en", models.CharField(help_text="VD: KCN Đại An mở rộng", max_length=255, null=True)),
                ("location_zh_hans", models.CharField(help_text="VD: KCN Đại An mở rộng", max_length=255, null=True)),
                ("location_ko", models.CharField(help_text="VD: KCN Đại An mở rộng", max_length=255, null=True)),
                ("province", models.CharField(help_text="VD: Hải Dương", max_length=100)),
                ("province_vi", models.CharField(help_text="VD: Hải Dương", max_length=100, null=True)),
                ("province_en", models.CharField(help_text="VD: Hải Dương", max_length=100, null=True)),
                ("province_zh_hans", models.CharField(help_text="VD: Hải Dương", max_length=100, null=True)),
                ("province_ko", models.CharField(help_text="VD: Hải Dương", max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "⑲ Dự án tiêu biểu",
                "verbose_name_plural": "⑲ Dự án tiêu biểu",
                "db_table": "pages_resource_projects",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        # ==================== PROJECTS PAGE ====================
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("name_vi", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_zh_hans", models.CharField(max_length=100, null=True)),
                ("name_ko", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "⑳ Danh mục dự án",
                "verbose_name_plural": "⑳ Danh mục dự án",
                "db_table": "pages_project_categories",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=500)),
                ("name_vi", models.CharField(max_length=500, null=True)),
                ("name_en", models.CharField(max_length=500, null=True)),
                ("name_zh_hans", models.CharField(max_length=500, null=True)),
                ("name_ko", models.CharField(max_length=500, null=True)),
                ("slug", models.SlugField(blank=True, max_length=500)),
                ("slug_vi", models.SlugField(blank=True, max_length=500, null=True)),
                ("slug_en", models.SlugField(blank=True, max_length=500, null=True)),
                ("slug_zh_hans", models.SlugField(blank=True, max_length=500, null=True)),
                ("slug_ko", models.SlugField(blank=True, max_length=500, null=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                ("image_vi", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("image_en", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("image_zh_hans", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("image_ko", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("location", models.CharField(blank=True, default="", help_text="VD: Nghệ An", max_length=255)),
                ("location_vi", models.CharField(blank=True, default="", help_text="VD: Nghệ An", max_length=255, null=True)),
                ("location_en", models.CharField(blank=True, default="", help_text="VD: Nghệ An", max_length=255, null=True)),
                ("location_zh_hans", models.CharField(blank=True, default="", help_text="VD: Nghệ An", max_length=255, null=True)),
                ("location_ko", models.CharField(blank=True, default="", help_text="VD: Nghệ An", max_length=255, null=True)),
                ("scale", models.CharField(blank=True, default="", help_text="VD: 1,114,060 m²", max_length=255)),
                ("scale_vi", models.CharField(blank=True, default="", help_text="VD: 1,114,060 m²", max_length=255, null=True)),
                ("scale_en", models.CharField(blank=True, default="", help_text="VD: 1,114,060 m²", max_length=255, null=True)),
                ("scale_zh_hans", models.CharField(blank=True, default="", help_text="VD: 1,114,060 m²", max_length=255, null=True)),
                ("scale_ko", models.CharField(blank=True, default="", help_text="VD: 1,114,060 m²", max_length=255, null=True)),
                ("progress", models.TextField(blank=True, default="", help_text="VD: 08/2023 ~ 10/2024")),
                ("progress_vi", models.TextField(blank=True, default="", help_text="VD: 08/2023 ~ 10/2024", null=True)),
                ("progress_en", models.TextField(blank=True, default="", help_text="VD: 08/2023 ~ 10/2024", null=True)),
                ("progress_zh_hans", models.TextField(blank=True, default="", help_text="VD: 08/2023 ~ 10/2024", null=True)),
                ("progress_ko", models.TextField(blank=True, default="", help_text="VD: 08/2023 ~ 10/2024", null=True)),
                ("year", models.CharField(blank=True, default="", help_text="Năm bắt đầu VD: 2023", max_length=10)),
                ("status", models.CharField(choices=[("ongoing", "Đang thực hiện"), ("completed", "Hoàn thành")], default="ongoing", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="projects", to="pages.projectcategory")),
            ],
            options={
                "verbose_name": "⑳ Dự án",
                "verbose_name_plural": "⑳ Dự án",
                "db_table": "pages_project_items",
                "ordering": ["-year", "-created_at"],
            },
        ),
    ]
