# Generated by Django 5.1.5 on 2026-04-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_business_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Họ tên', max_length=255)),
                ('email', models.EmailField(help_text='Email liên hệ', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Số điện thoại', max_length=50)),
                ('message', models.TextField(help_text='Nội dung tin nhắn')),
                ('is_read', models.BooleanField(default=False, help_text='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '㉒ Liên hệ',
                'verbose_name_plural': '㉒ Liên hệ',
                'db_table': 'pages_contact_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='businessfieldgallery',
            options={'ordering': ('order',), 'verbose_name': '㉑ Gallery lĩnh vực', 'verbose_name_plural': '㉑ Gallery lĩnh vực'},
        ),
        migrations.AlterModelOptions(
            name='businessfieldservice',
            options={'ordering': ('order',), 'verbose_name': '㉑ Dịch vụ lĩnh vực', 'verbose_name_plural': '㉑ Dịch vụ lĩnh vực'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('order',), 'verbose_name': '⑱ Chứng chỉ ISO', 'verbose_name_plural': '⑱ Chứng chỉ ISO'},
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ('order',), 'verbose_name': '⑩ Giá trị cốt lõi', 'verbose_name_plural': '⑩ Giá trị cốt lõi'},
        ),
        migrations.AlterModelOptions(
            name='historyitem',
            options={'ordering': ('order',), 'verbose_name': '⑨ Lịch sử', 'verbose_name_plural': '⑨ Lịch sử hình thành (Timeline)'},
        ),
        migrations.AlterModelOptions(
            name='leadershipmember',
            options={'ordering': ('order',), 'verbose_name': '⑫ Ban lãnh đạo', 'verbose_name_plural': '⑫ Ban lãnh đạo'},
        ),
        migrations.AlterModelOptions(
            name='organizationgalleryitem',
            options={'ordering': ('order',), 'verbose_name': '⑮ Thư viện ảnh (Cơ cấu tổ chức)', 'verbose_name_plural': '⑮ Thư viện ảnh (Cơ cấu tổ chức)'},
        ),
        migrations.AlterModelOptions(
            name='resourceproject',
            options={'ordering': ('order',), 'verbose_name': '⑲ Dự án tiêu biểu', 'verbose_name_plural': '⑲ Dự án tiêu biểu'},
        ),
        migrations.AlterModelOptions(
            name='staffbreakdown',
            options={'ordering': ('order',), 'verbose_name': '⑰ Nhân sự chi tiết', 'verbose_name_plural': '⑰ Nhân sự chi tiết'},
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image_en',
            field=models.ImageField(blank=True, help_text='Ảnh hiển thị khi share link lên Facebook, Zalo, LinkedIn...', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image_ko',
            field=models.ImageField(blank=True, help_text='Ảnh hiển thị khi share link lên Facebook, Zalo, LinkedIn...', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image_vi',
            field=models.ImageField(blank=True, help_text='Ảnh hiển thị khi share link lên Facebook, Zalo, LinkedIn...', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image_zh_hans',
            field=models.ImageField(blank=True, help_text='Ảnh hiển thị khi share link lên Facebook, Zalo, LinkedIn...', null=True, upload_to='seo/'),
        ),
    ]
