# Generated by Django 5.1.5 on 2026-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_newscategory_newsarticle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(blank=True, upload_to='achievements/gallery/')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('alt_vi', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('alt_en', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('alt_zh_hans', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('alt_ko', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '㉔ Thư viện ảnh (Thành tựu)',
                'verbose_name_plural': '㉔ Thư viện ảnh (Thành tựu)',
                'db_table': 'pages_achievement_gallery',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('year', models.CharField(help_text='Năm nhận giải, VD: 2024', max_length=10)),
                ('title', models.CharField(help_text='Tên giải thưởng', max_length=500)),
                ('title_vi', models.CharField(help_text='Tên giải thưởng', max_length=500, null=True)),
                ('title_en', models.CharField(help_text='Tên giải thưởng', max_length=500, null=True)),
                ('title_zh_hans', models.CharField(help_text='Tên giải thưởng', max_length=500, null=True)),
                ('title_ko', models.CharField(help_text='Tên giải thưởng', max_length=500, null=True)),
                ('organization', models.CharField(blank=True, default='', help_text='Đơn vị trao giải', max_length=255)),
                ('organization_vi', models.CharField(blank=True, default='', help_text='Đơn vị trao giải', max_length=255, null=True)),
                ('organization_en', models.CharField(blank=True, default='', help_text='Đơn vị trao giải', max_length=255, null=True)),
                ('organization_zh_hans', models.CharField(blank=True, default='', help_text='Đơn vị trao giải', max_length=255, null=True)),
                ('organization_ko', models.CharField(blank=True, default='', help_text='Đơn vị trao giải', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Mô tả chi tiết')),
                ('description_vi', models.TextField(blank=True, default='', help_text='Mô tả chi tiết', null=True)),
                ('description_en', models.TextField(blank=True, default='', help_text='Mô tả chi tiết', null=True)),
                ('description_zh_hans', models.TextField(blank=True, default='', help_text='Mô tả chi tiết', null=True)),
                ('description_ko', models.TextField(blank=True, default='', help_text='Mô tả chi tiết', null=True)),
                ('image', models.ImageField(blank=True, upload_to='achievements/awards/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '㉓ Giải thưởng',
                'verbose_name_plural': '㉓ Giải thưởng & Thành tựu',
                'db_table': 'pages_awards',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
