volumes:
  hopluccorp_local_postgres_data: {}
  hopluccorp_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: hopluccorp_local_django
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - hopluccorp_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PGTZ=Asia/Ho_Chi_Minh
    command: postgres -c timezone=Asia/Ho_Chi_Minh

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - hopluccorp_local_redis_data:/data
    ports:
      - "6381:6379"

  celeryworker:
    <<: *django
    image: hopluccorp_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: hopluccorp_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: hopluccorp_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
