from django.core.management.base import BaseCommand

from hopluccorp.pages.models import ProjectCategory, ProjectItem


CATEGORIES = [
    {
        "slug": "cong-nghiep",
        "name_vi": "Công nghiệp",
        "name_en": "Industrial",
        "name_zh_hans": "工业",
        "name_ko": "산업",
    },
    {
        "slug": "dan-dung",
        "name_vi": "Dân dụng",
        "name_en": "Civil",
        "name_zh_hans": "民用",
        "name_ko": "민간",
    },
    {
        "slug": "ha-tang",
        "name_vi": "Hạ tầng",
        "name_en": "Infrastructure",
        "name_zh_hans": "基础设施",
        "name_ko": "인프라",
    },
]

# Tên dự án là tên riêng (proper nouns) — giữ nguyên tên VI cho EN/ZH/KO
# Location được dịch sang EN/ZH/KO
# Scale và Progress giữ nguyên (số liệu)
PROJECTS = [
    {
        "slug_vi": "nha-may-luxshare-ict-nghe-an-2",
        "slug_en": "luxshare-ict-factory-nghe-an-2",
        "slug_zh_hans": "luxshare-ict-nghe-an-2",
        "slug_ko": "luxshare-ict-nghe-an-2",
        "name_vi": "NHÀ MÁY LUXSHARE-ICT (NGHỆ AN) 2",
        "name_en": "LUXSHARE-ICT FACTORY (NGHE AN) 2",
        "name_zh_hans": "LUXSHARE-ICT工厂（义安）2",
        "name_ko": "LUXSHARE-ICT 공장 (응에안) 2",
        "category_slug": "cong-nghiep",
        "location_vi": "Nghệ An",
        "location_en": "Nghe An",
        "location_zh_hans": "义安省",
        "location_ko": "응에안성",
        "scale_vi": "1,114,060 m²",
        "scale_en": "1,114,060 m²",
        "scale_zh_hans": "1,114,060 m²",
        "scale_ko": "1,114,060 m²",
        "progress_vi": "08/2023 ~ 10/2024\n07/2024 ~ 03/2025",
        "progress_en": "08/2023 ~ 10/2024\n07/2024 ~ 03/2025",
        "progress_zh_hans": "08/2023 ~ 10/2024\n07/2024 ~ 03/2025",
        "progress_ko": "08/2023 ~ 10/2024\n07/2024 ~ 03/2025",
        "year": 2023,
        "status": "ongoing",
    },
    {
        "slug_vi": "nha-may-san-xuat-van-phong-pham-tap-doan-deli-vet-nam",
        "slug_en": "deli-vietnam-stationery-factory",
        "slug_zh_hans": "deli-vietnam-stationery-factory",
        "slug_ko": "deli-vietnam-stationery-factory",
        "name_vi": "NHÀ MÁY SẢN XUẤT VĂN PHÒNG PHẨM TẬP ĐOÀN DELI VIỆT NAM",
        "name_en": "DELI VIETNAM STATIONERY MANUFACTURING FACTORY",
        "name_zh_hans": "得力越南文具制造工厂",
        "name_ko": "DELI 베트남 문구 제조 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Hải Dương",
        "location_en": "Hai Duong",
        "location_zh_hans": "海阳省",
        "location_ko": "하이즈엉성",
        "scale_vi": "144,152 m²",
        "scale_en": "144,152 m²",
        "scale_zh_hans": "144,152 m²",
        "scale_ko": "144,152 m²",
        "progress_vi": "09/2024 ~ 03/2026",
        "progress_en": "09/2024 ~ 03/2026",
        "progress_zh_hans": "09/2024 ~ 03/2026",
        "progress_ko": "09/2024 ~ 03/2026",
        "year": 2024,
        "status": "ongoing",
    },
    {
        "slug_vi": "nha-may-foxconn-nghe-an",
        "slug_en": "foxconn-factory-nghe-an",
        "slug_zh_hans": "foxconn-factory-nghe-an",
        "slug_ko": "foxconn-factory-nghe-an",
        "name_vi": "NHÀ MÁY FOXCONN NGHỆ AN",
        "name_en": "FOXCONN FACTORY NGHE AN",
        "name_zh_hans": "富士康工厂（义安）",
        "name_ko": "폭스콘 공장 응에안",
        "category_slug": "cong-nghiep",
        "location_vi": "Nghệ An",
        "location_en": "Nghe An",
        "location_zh_hans": "义安省",
        "location_ko": "응에안성",
        "scale_vi": "68,541 m²",
        "scale_en": "68,541 m²",
        "scale_zh_hans": "68,541 m²",
        "scale_ko": "68,541 m²",
        "progress_vi": "06/2024 ~ 12/2024",
        "progress_en": "06/2024 ~ 12/2024",
        "progress_zh_hans": "06/2024 ~ 12/2024",
        "progress_ko": "06/2024 ~ 12/2024",
        "year": 2024,
        "status": "completed",
    },
    {
        "slug_vi": "nha-xuong-xay-san-va-van-phong-cho-thue-spectrum-nghe-an",
        "slug_en": "soilbuild-ready-built-factory-nghe-an",
        "slug_zh_hans": "soilbuild-ready-built-factory-nghe-an",
        "slug_ko": "soilbuild-ready-built-factory-nghe-an",
        "name_vi": "NHÀ XƯỞNG XÂY SẴN VÀ VĂN PHÒNG CHO THUÊ SOILBUILD NGHỆ AN",
        "name_en": "SOILBUILD READY-BUILT FACTORY & OFFICE FOR RENT NGHE AN",
        "name_zh_hans": "SOILBUILD预建厂房及出租办公室（义安）",
        "name_ko": "SOILBUILD 기성 공장 및 임대 사무실 응에안",
        "category_slug": "cong-nghiep",
        "location_vi": "Nghệ An",
        "location_en": "Nghe An",
        "location_zh_hans": "义安省",
        "location_ko": "응에안성",
        "scale_vi": "42,844 m²",
        "scale_en": "42,844 m²",
        "scale_zh_hans": "42,844 m²",
        "scale_ko": "42,844 m²",
        "progress_vi": "07/2024 ~ 02/2025",
        "progress_en": "07/2024 ~ 02/2025",
        "progress_zh_hans": "07/2024 ~ 02/2025",
        "progress_ko": "07/2024 ~ 02/2025",
        "year": 2024,
        "status": "ongoing",
    },
    {
        "slug_vi": "nha-may-cong-ty-tnhh-cong-nghe-thong-minh-goertek-vina",
        "slug_en": "goertek-vina-smart-technology-factory",
        "slug_zh_hans": "goertek-vina-smart-technology-factory",
        "slug_ko": "goertek-vina-smart-technology-factory",
        "name_vi": "NHÀ MÁY CÔNG TY TNHH CÔNG NGHỆ THÔNG MINH GOERTEK VINA",
        "name_en": "GOERTEK VINA SMART TECHNOLOGY FACTORY",
        "name_zh_hans": "歌尔VINA智能科技工厂",
        "name_ko": "GOERTEK VINA 스마트 기술 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Bắc Ninh",
        "location_en": "Bac Ninh",
        "location_zh_hans": "北宁省",
        "location_ko": "박닌성",
        "scale_vi": "582,268 m²",
        "scale_en": "582,268 m²",
        "scale_zh_hans": "582,268 m²",
        "scale_ko": "582,268 m²",
        "progress_vi": "05/2023 ~ 05/2025",
        "progress_en": "05/2023 ~ 05/2025",
        "progress_zh_hans": "05/2023 ~ 05/2025",
        "progress_ko": "05/2023 ~ 05/2025",
        "year": 2023,
        "status": "ongoing",
    },
    {
        "slug_vi": "nha-may-dien-tu-byd-viet-nam",
        "slug_en": "byd-electronics-factory-vietnam",
        "slug_zh_hans": "byd-electronics-factory-vietnam",
        "slug_ko": "byd-electronics-factory-vietnam",
        "name_vi": "NHÀ MÁY ĐIỆN TỬ BYD (VIỆT NAM)",
        "name_en": "BYD ELECTRONICS FACTORY (VIETNAM)",
        "name_zh_hans": "比亚迪电子工厂（越南）",
        "name_ko": "BYD 전자 공장 (베트남)",
        "category_slug": "cong-nghiep",
        "location_vi": "Phú Thọ",
        "location_en": "Phu Tho",
        "location_zh_hans": "富寿省",
        "location_ko": "푸토성",
        "scale_vi": "388,105 m²",
        "scale_en": "388,105 m²",
        "scale_zh_hans": "388,105 m²",
        "scale_ko": "388,105 m²",
        "progress_vi": "10/2021 ~ 08/2025",
        "progress_en": "10/2021 ~ 08/2025",
        "progress_zh_hans": "10/2021 ~ 08/2025",
        "progress_ko": "10/2021 ~ 08/2025",
        "year": 2021,
        "status": "ongoing",
    },
    {
        "slug_vi": "nha-may-solex-high-tech-industries-viet-nam",
        "slug_en": "solex-high-tech-industries-factory-vietnam",
        "slug_zh_hans": "solex-high-tech-industries-factory-vietnam",
        "slug_ko": "solex-high-tech-industries-factory-vietnam",
        "name_vi": "NHÀ MÁY SOLEX HIGH-TECH INDUSTRIES (VIỆT NAM)",
        "name_en": "SOLEX HIGH-TECH INDUSTRIES FACTORY (VIETNAM)",
        "name_zh_hans": "SOLEX高科技工业工厂（越南）",
        "name_ko": "SOLEX 하이테크 산업 공장 (베트남)",
        "category_slug": "cong-nghiep",
        "location_vi": "Quảng Ninh",
        "location_en": "Quang Ninh",
        "location_zh_hans": "广宁省",
        "location_ko": "꽝닌성",
        "scale_vi": "46,517 m²",
        "scale_en": "46,517 m²",
        "scale_zh_hans": "46,517 m²",
        "scale_ko": "46,517 m²",
        "progress_vi": "11/2023 ~ 10/2024",
        "progress_en": "11/2023 ~ 10/2024",
        "progress_zh_hans": "11/2023 ~ 10/2024",
        "progress_ko": "11/2023 ~ 10/2024",
        "year": 2023,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-desay-battery-vina",
        "slug_en": "desay-battery-vina-factory",
        "slug_zh_hans": "desay-battery-vina-factory",
        "slug_ko": "desay-battery-vina-factory",
        "name_vi": "NHÀ MÁY DESAY BATTERY VINA",
        "name_en": "DESAY BATTERY VINA FACTORY",
        "name_zh_hans": "德赛电池VINA工厂",
        "name_ko": "DESAY BATTERY VINA 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Bắc Giang",
        "location_en": "Bac Giang",
        "location_zh_hans": "北江省",
        "location_ko": "박장성",
        "scale_vi": "27,738 m²",
        "scale_en": "27,738 m²",
        "scale_zh_hans": "27,738 m²",
        "scale_ko": "27,738 m²",
        "progress_vi": "03/2022 ~ 04/2023",
        "progress_en": "03/2022 ~ 04/2023",
        "progress_zh_hans": "03/2022 ~ 04/2023",
        "progress_ko": "03/2022 ~ 04/2023",
        "year": 2022,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-innovation-precision-viet-nam",
        "slug_en": "innovation-precision-factory-vietnam",
        "slug_zh_hans": "innovation-precision-factory-vietnam",
        "slug_ko": "innovation-precision-factory-vietnam",
        "name_vi": "NHÀ MÁY INNOVATION PRECISION VIỆT NAM",
        "name_en": "INNOVATION PRECISION FACTORY VIETNAM",
        "name_zh_hans": "INNOVATION PRECISION越南工厂",
        "name_ko": "INNOVATION PRECISION 베트남 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Nghệ An",
        "location_en": "Nghe An",
        "location_zh_hans": "义安省",
        "location_ko": "응에안성",
        "scale_vi": "94,297 m²",
        "scale_en": "94,297 m²",
        "scale_zh_hans": "94,297 m²",
        "scale_ko": "94,297 m²",
        "progress_vi": "09/2023 ~ 05/2024",
        "progress_en": "09/2023 ~ 05/2024",
        "progress_zh_hans": "09/2023 ~ 05/2024",
        "progress_ko": "09/2023 ~ 05/2024",
        "year": 2023,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-cot-viet-nam",
        "slug_en": "cot-factory-vietnam",
        "slug_zh_hans": "cot-factory-vietnam",
        "slug_ko": "cot-factory-vietnam",
        "name_vi": "NHÀ MÁY COT VIỆT NAM",
        "name_en": "COT FACTORY VIETNAM",
        "name_zh_hans": "COT越南工厂",
        "name_ko": "COT 베트남 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Hưng Yên",
        "location_en": "Hung Yen",
        "location_zh_hans": "兴安省",
        "location_ko": "흥옌성",
        "scale_vi": "82,500 m²",
        "scale_en": "82,500 m²",
        "scale_zh_hans": "82,500 m²",
        "scale_ko": "82,500 m²",
        "progress_vi": "12/2023 ~ 09/2024",
        "progress_en": "12/2023 ~ 09/2024",
        "progress_zh_hans": "12/2023 ~ 09/2024",
        "progress_ko": "12/2023 ~ 09/2024",
        "year": 2023,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-sunny-automotive-quang-hoc-viet-nam",
        "slug_en": "sunny-automotive-optics-factory-vietnam",
        "slug_zh_hans": "sunny-automotive-optics-factory-vietnam",
        "slug_ko": "sunny-automotive-optics-factory-vietnam",
        "name_vi": "NHÀ MÁY SUNNY AUTOMOTIVE QUANG HỌC VIỆT NAM",
        "name_en": "SUNNY AUTOMOTIVE OPTICS FACTORY VIETNAM",
        "name_zh_hans": "舜宇车载光学越南工厂",
        "name_ko": "SUNNY AUTOMOTIVE 광학 베트남 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Nghệ An",
        "location_en": "Nghe An",
        "location_zh_hans": "义安省",
        "location_ko": "응에안성",
        "scale_vi": "120,000 m²",
        "scale_en": "120,000 m²",
        "scale_zh_hans": "120,000 m²",
        "scale_ko": "120,000 m²",
        "progress_vi": "01/2024 ~ 12/2024",
        "progress_en": "01/2024 ~ 12/2024",
        "progress_zh_hans": "01/2024 ~ 12/2024",
        "progress_ko": "01/2024 ~ 12/2024",
        "year": 2024,
        "status": "ongoing",
    },
    {
        "slug_vi": "nha-may-luxshare-ict-nghe-an",
        "slug_en": "luxshare-ict-factory-nghe-an",
        "slug_zh_hans": "luxshare-ict-factory-nghe-an",
        "slug_ko": "luxshare-ict-factory-nghe-an",
        "name_vi": "NHÀ MÁY LUXSHARE-ICT (NGHỆ AN)",
        "name_en": "LUXSHARE-ICT FACTORY (NGHE AN)",
        "name_zh_hans": "LUXSHARE-ICT工厂（义安）",
        "name_ko": "LUXSHARE-ICT 공장 (응에안)",
        "category_slug": "cong-nghiep",
        "location_vi": "Nghệ An",
        "location_en": "Nghe An",
        "location_zh_hans": "义安省",
        "location_ko": "응에안성",
        "scale_vi": "250,000 m²",
        "scale_en": "250,000 m²",
        "scale_zh_hans": "250,000 m²",
        "scale_ko": "250,000 m²",
        "progress_vi": "2020 ~ 2023",
        "progress_en": "2020 ~ 2023",
        "progress_zh_hans": "2020 ~ 2023",
        "progress_ko": "2020 ~ 2023",
        "year": 2020,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-dbg-technology-viet-nam",
        "slug_en": "dbg-technology-factory-vietnam",
        "slug_zh_hans": "dbg-technology-factory-vietnam",
        "slug_ko": "dbg-technology-factory-vietnam",
        "name_vi": "NHÀ MÁY DBG TECHNOLOGY VIỆT NAM",
        "name_en": "DBG TECHNOLOGY FACTORY VIETNAM",
        "name_zh_hans": "DBG科技越南工厂",
        "name_ko": "DBG 기술 베트남 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Thái Nguyên",
        "location_en": "Thai Nguyen",
        "location_zh_hans": "太原省",
        "location_ko": "타이응우옌성",
        "scale_vi": "150,000 m²",
        "scale_en": "150,000 m²",
        "scale_zh_hans": "150,000 m²",
        "scale_ko": "150,000 m²",
        "progress_vi": "2022 ~ 2024",
        "progress_en": "2022 ~ 2024",
        "progress_zh_hans": "2022 ~ 2024",
        "progress_ko": "2022 ~ 2024",
        "year": 2022,
        "status": "completed",
    },
    {
        "slug_vi": "slp-bac-ninh-logistic",
        "slug_en": "slp-bac-ninh-logistics",
        "slug_zh_hans": "slp-bac-ninh-logistics",
        "slug_ko": "slp-bac-ninh-logistics",
        "name_vi": "SLP BẮC NINH LOGISTIC",
        "name_en": "SLP BAC NINH LOGISTICS",
        "name_zh_hans": "SLP北宁物流",
        "name_ko": "SLP 박닌 물류",
        "category_slug": "cong-nghiep",
        "location_vi": "Bắc Ninh",
        "location_en": "Bac Ninh",
        "location_zh_hans": "北宁省",
        "location_ko": "박닌성",
        "scale_vi": "95,000 m²",
        "scale_en": "95,000 m²",
        "scale_zh_hans": "95,000 m²",
        "scale_ko": "95,000 m²",
        "progress_vi": "2023 ~ 2024",
        "progress_en": "2023 ~ 2024",
        "progress_zh_hans": "2023 ~ 2024",
        "progress_ko": "2023 ~ 2024",
        "year": 2023,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-cayi-technology-viet-nam",
        "slug_en": "cayi-technology-factory-vietnam",
        "slug_zh_hans": "cayi-technology-factory-vietnam",
        "slug_ko": "cayi-technology-factory-vietnam",
        "name_vi": "NHÀ MÁY CAYI TECHNOLOGY VIỆT NAM",
        "name_en": "CAYI TECHNOLOGY FACTORY VIETNAM",
        "name_zh_hans": "CAYI科技越南工厂",
        "name_ko": "CAYI 기술 베트남 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Bắc Ninh",
        "location_en": "Bac Ninh",
        "location_zh_hans": "北宁省",
        "location_ko": "박닌성",
        "scale_vi": "85,000 m²",
        "scale_en": "85,000 m²",
        "scale_zh_hans": "85,000 m²",
        "scale_ko": "85,000 m²",
        "progress_vi": "2023 ~ 2024",
        "progress_en": "2023 ~ 2024",
        "progress_zh_hans": "2023 ~ 2024",
        "progress_ko": "2023 ~ 2024",
        "year": 2023,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-song-hong-xuan-truong-ii",
        "slug_en": "song-hong-xuan-truong-ii-factory",
        "slug_zh_hans": "song-hong-xuan-truong-ii-factory",
        "slug_ko": "song-hong-xuan-truong-ii-factory",
        "name_vi": "NHÀ MÁY SÔNG HỒNG - XUÂN TRƯỜNG II",
        "name_en": "SONG HONG - XUAN TRUONG II FACTORY",
        "name_zh_hans": "红河-春长II工厂",
        "name_ko": "송홍 - 쑤언쯔엉 II 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Nam Định",
        "location_en": "Nam Dinh",
        "location_zh_hans": "南定省",
        "location_ko": "남딘성",
        "scale_vi": "75,000 m²",
        "scale_en": "75,000 m²",
        "scale_zh_hans": "75,000 m²",
        "scale_ko": "75,000 m²",
        "progress_vi": "2023 ~ 2024",
        "progress_en": "2023 ~ 2024",
        "progress_zh_hans": "2023 ~ 2024",
        "progress_ko": "2023 ~ 2024",
        "year": 2023,
        "status": "completed",
    },
    {
        "slug_vi": "khu-nha-o-can-bo-nhiet-dien-vung-ang-2",
        "slug_en": "vung-ang-2-thermal-power-staff-housing",
        "slug_zh_hans": "vung-ang-2-thermal-power-staff-housing",
        "slug_ko": "vung-ang-2-thermal-power-staff-housing",
        "name_vi": "KHU NHÀ Ở CÁN BỘ NHIỆT ĐIỆN VŨNG ÁNG 2",
        "name_en": "VUNG ANG 2 THERMAL POWER STAFF HOUSING",
        "name_zh_hans": "永昂2号热电厂员工住宅区",
        "name_ko": "붕앙 2 화력발전소 직원 주거단지",
        "category_slug": "dan-dung",
        "location_vi": "Hà Tĩnh",
        "location_en": "Ha Tinh",
        "location_zh_hans": "河静省",
        "location_ko": "하띤성",
        "scale_vi": "35,000 m²",
        "scale_en": "35,000 m²",
        "scale_zh_hans": "35,000 m²",
        "scale_ko": "35,000 m²",
        "progress_vi": "2022 ~ 2023",
        "progress_en": "2022 ~ 2023",
        "progress_zh_hans": "2022 ~ 2023",
        "progress_ko": "2022 ~ 2023",
        "year": 2022,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-san-xuat-mdf-mekong",
        "slug_en": "mekong-mdf-manufacturing-factory",
        "slug_zh_hans": "mekong-mdf-manufacturing-factory",
        "slug_ko": "mekong-mdf-manufacturing-factory",
        "name_vi": "NHÀ MÁY SẢN XUẤT MDF MEKONG",
        "name_en": "MEKONG MDF MANUFACTURING FACTORY",
        "name_zh_hans": "湄公河MDF制造工厂",
        "name_ko": "MEKONG MDF 제조 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Phú Thọ",
        "location_en": "Phu Tho",
        "location_zh_hans": "富寿省",
        "location_ko": "푸토성",
        "scale_vi": "65,000 m²",
        "scale_en": "65,000 m²",
        "scale_zh_hans": "65,000 m²",
        "scale_ko": "65,000 m²",
        "progress_vi": "2021 ~ 2022",
        "progress_en": "2021 ~ 2022",
        "progress_zh_hans": "2021 ~ 2022",
        "progress_ko": "2021 ~ 2022",
        "year": 2021,
        "status": "completed",
    },
    {
        "slug_vi": "nha-may-hw-energy",
        "slug_en": "hw-energy-factory",
        "slug_zh_hans": "hw-energy-factory",
        "slug_ko": "hw-energy-factory",
        "name_vi": "NHÀ MÁY HW ENERGY",
        "name_en": "HW ENERGY FACTORY",
        "name_zh_hans": "HW能源工厂",
        "name_ko": "HW ENERGY 공장",
        "category_slug": "cong-nghiep",
        "location_vi": "Hải Phòng",
        "location_en": "Hai Phong",
        "location_zh_hans": "海防市",
        "location_ko": "하이퐁시",
        "scale_vi": "55,000 m²",
        "scale_en": "55,000 m²",
        "scale_zh_hans": "55,000 m²",
        "scale_ko": "55,000 m²",
        "progress_vi": "2024 ~ 2025",
        "progress_en": "2024 ~ 2025",
        "progress_zh_hans": "2024 ~ 2025",
        "progress_ko": "2024 ~ 2025",
        "year": 2024,
        "status": "ongoing",
    },
]


class Command(BaseCommand):
    help = "Seed projects data (categories + 19 projects) with full i18n (vi/en/zh/ko)"

    def add_arguments(self, parser):
        parser.add_argument("--reset", action="store_true", help="Delete existing data before seeding")

    def handle(self, *args, **options):
        if options["reset"]:
            ProjectItem.objects.all().delete()
            ProjectCategory.objects.all().delete()
            self.stdout.write(self.style.WARNING("Deleted all projects data"))

        # ── Categories ──
        if not ProjectCategory.objects.exists():
            for data in CATEGORIES:
                ProjectCategory.objects.create(
                    slug=data["slug"],
                    name=data["name_vi"],
                    name_vi=data["name_vi"],
                    name_en=data["name_en"],
                    name_zh_hans=data["name_zh_hans"],
                    name_ko=data["name_ko"],
                )
            self.stdout.write(self.style.SUCCESS(f"Created {len(CATEGORIES)} project categories"))

        # ── Projects ──
        if not ProjectItem.objects.exists():
            cat_map = {c.slug: c for c in ProjectCategory.objects.all()}
            created = 0
            for data in PROJECTS:
                category = cat_map.get(data["category_slug"])
                ProjectItem.objects.create(
                    category=category,
                    slug=data["slug_vi"],
                    slug_vi=data["slug_vi"],
                    slug_en=data["slug_en"],
                    slug_zh_hans=data["slug_zh_hans"],
                    slug_ko=data["slug_ko"],
                    name=data["name_vi"],
                    name_vi=data["name_vi"],
                    name_en=data["name_en"],
                    name_zh_hans=data["name_zh_hans"],
                    name_ko=data["name_ko"],
                    location=data["location_vi"],
                    location_vi=data["location_vi"],
                    location_en=data["location_en"],
                    location_zh_hans=data["location_zh_hans"],
                    location_ko=data["location_ko"],
                    scale=data["scale_vi"],
                    scale_vi=data["scale_vi"],
                    scale_en=data["scale_en"],
                    scale_zh_hans=data["scale_zh_hans"],
                    scale_ko=data["scale_ko"],
                    progress=data["progress_vi"],
                    progress_vi=data["progress_vi"],
                    progress_en=data["progress_en"],
                    progress_zh_hans=data["progress_zh_hans"],
                    progress_ko=data["progress_ko"],
                    year=data["year"],
                    status=data["status"],
                )
                created += 1
            self.stdout.write(self.style.SUCCESS(f"Created {created} projects with i18n"))

        self.stdout.write(self.style.SUCCESS("Projects seed complete!"))
